"""add_maintenance_module

Revision ID: 3d0da7ae3ed8
Revises: ecb18635f3c0
Create Date: 2026-03-02 19:01:35.055551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d0da7ae3ed8'
down_revision: Union[str, None] = 'ecb18635f3c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maint_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rut', sa.String(), nullable=False),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maint_providers_rut'), 'maint_providers', ['rut'], unique=True)
    op.create_table('maint_provider_equipment_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('equipment_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['maint_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maint_equipment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('equipment_type', sa.Enum('EXCAVATOR', 'CRANE', 'TRUCK', 'GENERATOR', 'COMPRESSOR', 'PUMP', 'FORKLIFT', 'OTHER', name='equipmenttype'), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('model_year', sa.Integer(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('OPERATIVE', 'IN_TRANSIT', 'IN_MAINTENANCE', 'OUT_OF_SERVICE', 'SCRAPPED', name='equipmentstatus'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('cost_center_id', sa.UUID(), nullable=True),
    sa.Column('current_horometer', sa.Numeric(precision=10, scale=1), nullable=False),
    sa.Column('maintenance_interval_hours', sa.Integer(), nullable=False),
    sa.Column('last_maintenance_date', sa.DateTime(), nullable=True),
    sa.Column('next_maintenance_due', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('last_certificate_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], ),
    sa.ForeignKeyConstraint(['last_certificate_id'], ['maint_certificates.id'], name='fk_maint_equipment_last_cert', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maint_equipment_code'), 'maint_equipment', ['code'], unique=True)
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maint_horometer_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('reading', sa.Numeric(precision=10, scale=1), nullable=False),
    sa.Column('previous_reading', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('hours_delta', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('recorded_by_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['maint_equipment.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maint_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('requested_by_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('maintenance_type', sa.Enum('PREVENTIVE', 'CORRECTIVE', 'PREDICTIVE', 'OVERHAUL', name='maintenancetype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'AWAITING_PREREQUISITES', 'READY_FOR_EXECUTION', 'IN_TRANSIT_TO_WORKSHOP', 'IN_MAINTENANCE', 'PENDING_RECEPTION', 'PENDING_CERTIFICATE', 'IN_TRANSIT_TO_FIELD', 'COMPLETED', 'REJECTED', 'CANCELLED', name='maintrequeststatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('planned_date', sa.DateTime(), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('sgp_request_id', sa.UUID(), nullable=True),
    sa.Column('purchase_order_code', sa.String(), nullable=True),
    sa.Column('provider_confirmed', sa.Boolean(), nullable=False),
    sa.Column('transport_scheduled', sa.Boolean(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('invoice_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('remediation_deadline', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['maint_equipment.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['maint_providers.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sgp_request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maint_requests_code'), 'maint_requests', ['code'], unique=True)
    op.create_table('maint_certificates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('maint_request_id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['maint_equipment.id'], ),
    sa.ForeignKeyConstraint(['maint_request_id'], ['maint_requests.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maint_reception_checklists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('maint_request_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('overall_result', sa.Enum('PASS', 'FAIL', 'PARTIAL', name='checklistresult'), nullable=False),
    sa.Column('mechanical_group', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('electrical_group', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hydraulic_group', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('safety_group', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['maint_request_id'], ['maint_requests.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('maint_request_id')
    )
    op.create_table('maint_transport_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('maint_request_id', sa.UUID(), nullable=False),
    sa.Column('trip_type', sa.Enum('TO_WORKSHOP', 'TO_FIELD', name='triptype'), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_TRANSIT', 'COMPLETED', 'CANCELLED', name='transportstatus'), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('actual_date', sa.DateTime(), nullable=True),
    sa.Column('transport_company', sa.String(), nullable=True),
    sa.Column('driver_name', sa.String(), nullable=True),
    sa.Column('driver_phone', sa.String(), nullable=True),
    sa.Column('plate_number', sa.String(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['maint_request_id'], ['maint_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maint_workflow_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('maint_request_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'AWAITING_PREREQUISITES', 'READY_FOR_EXECUTION', 'IN_TRANSIT_TO_WORKSHOP', 'IN_MAINTENANCE', 'PENDING_RECEPTION', 'PENDING_CERTIFICATE', 'IN_TRANSIT_TO_FIELD', 'COMPLETED', 'REJECTED', 'CANCELLED', name='maintrequeststatus'), nullable=True),
    sa.Column('to_status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'AWAITING_PREREQUISITES', 'READY_FOR_EXECUTION', 'IN_TRANSIT_TO_WORKSHOP', 'IN_MAINTENANCE', 'PENDING_RECEPTION', 'PENDING_CERTIFICATE', 'IN_TRANSIT_TO_FIELD', 'COMPLETED', 'REJECTED', 'CANCELLED', name='maintrequeststatus'), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['maint_request_id'], ['maint_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maint_workflow_logs_maint_request_id'), 'maint_workflow_logs', ['maint_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maint_workflow_logs_maint_request_id'), table_name='maint_workflow_logs')
    op.drop_table('maint_workflow_logs')
    op.drop_table('maint_transport_schedules')
    op.drop_table('maint_reception_checklists')
    op.drop_table('maint_certificates')
    op.drop_index(op.f('ix_maint_requests_code'), table_name='maint_requests')
    op.drop_table('maint_requests')
    op.drop_table('maint_horometer_logs')
    op.drop_table('comments')
    op.drop_index(op.f('ix_maint_equipment_code'), table_name='maint_equipment')
    op.drop_table('maint_equipment')
    op.drop_table('maint_provider_equipment_types')
    op.drop_index(op.f('ix_maint_providers_rut'), table_name='maint_providers')
    op.drop_table('maint_providers')
    # ### end Alembic commands ###
